### ISSUE TITLE
Worse object clipping problem than in ammojs-typed

### ISSUE THREAD

**Issue by AndyGura** [i12345/ammo.js#1]
I'm trying to migrate my engine integration to use `ammojs3` instead of `ammojs-typed` because it's more up to date and gives much more convenient API. But the problem is, even though it gives similar performance, objects clip through each other much more often with exactly the same world setup. I'm not ready to provide small code example, but here is the scene, built with [ammojs-typed](https://gg-web-demos.guraklgames.com/collision-groups-pool-three-ammo/index.html) and one with [ammojs3](https://gg-web-demos.guraklgames.com/collision-groups-pool-three-ammojs3/index.html). The issue is obvious when you play with sliders.

World setup can be found [here](https://github.com/AndyGura/gg-web-engine/blob/main/packages/ammo/src/components/ammo-world.component.ts) - it uses ammojs-typed, but for ammojs3 I used exactly this setup.

Any idea what can cause this and how to overcome this problem? Thanks!

**Comment by i12345** [comment]
This is a very interesting setup; I see how the spheres are clipped into fast-moving objects.

I record a video of using your example. Frame by frame, it appears that this is happening:

```typescript
updatePhysics()
floor.position.y = // ...
render()
```

The floor position appears to be updated after physics is calculated. The physics will be stable, but the position of the spheres is one frame behind the position of the floor.

Carefully playing this [screen recording \[webm\]](https://github.com/i12345/ammo.js/assets/81106451/6c7888a1-525e-4c6b-99ac-d67eca47a344), you can see this is in the first few frames.

**Comment by AndyGura** [comment]
Hey @i12345 ! Thanks for your reply. Solid point about order when physics is updated. When I update floor position after physics simulation it indeed makes it way worse. But in this case I double-checked, that's not the case. + even if true, still a mistery why it behaves worse than ammojs-typed example.

Here, I made a simplified example, which reproduces the problem, without using ammo integration module from my engine for clean experiment: https://stackblitz.com/edit/typescript-rblr8a?file=index.ts

There I have one single test case, the same scene, the same rules, and two physics backend files, one with ammojs-typed, second with ammojs3. You can check them - they exactly the same, only import differs and some names changed to avoid confusion. I update floor before physics simulation, you can check by changing `- 1` to `+ 1` on line 51: ```createInlineTickController(currentWorld, TickOrder.PHYSICS_SIMULATION - 1)```. The problem is clearly seen: 
https://github.com/i12345/ammo.js/assets/9253105/06140ec8-df1c-4592-9ccf-b01bd874d415 . Any ideas how to fix that?

Meanwhile I setup my own bullet building environment, because I require some patches in C++ code and I will try to walk through the git and determine at what point it started to happen and why

**Comment by AndyGura** [comment]
If anyone interested, I narrowed down the issue to this tiny commit to bullet: https://github.com/bulletphysics/bullet3/commit/96c1ee42565d951347e515e40f41f71d0963d2d0

After this change the behavior changed just like on video and example above.

I opened a PR to this repo to give the caller code ability to change these parameters: https://github.com/i12345/ammo.js/pull/2
